import type { Story } from "./content";

/* Economie și internațional. Persoanele sunt fictive. */
export const STORIES_B: Story[] = [
  {
    id: "bnr-dobanda",
    category: "economie",
    image: { scene: "city", caption: "Palatul Băncii Naționale a României", hue: 40 },
    versions: [
      {
        outlet: "radareconomic",
        title: "BNR menține dobânda de politică monetară la 6,50% pentru a opta ședință consecutiv",
        subheading: "Ce urmează pentru rate",
        author: "Diana Voicu",
        offsetMin: 150,
        quoteBy: "Cornel Sava",
        paragraphs: [
          "Consiliul de administrație al Băncii Naționale a României a decis marți menținerea ratei dobânzii de politică monetară la 6,50% pe an, în linie cu așteptările analiștilor. Rata dobânzii pentru facilitatea de creditare rămâne la 7,50%, iar cea pentru facilitatea de depozit la 5,50%.",
          "Banca centrală a păstrat și nivelurile actuale ale rezervelor minime obligatorii pentru pasivele în lei și în valută ale băncilor.",
          "În comunicatul transmis după ședință, BNR arată că rata anuală a inflației a continuat să scadă în ultimele luni, însă rămâne peste intervalul țintei, iar incertitudinile legate de politica fiscală sunt în continuare ridicate.",
          "„Cred că prima reducere a dobânzii o vom vedea cel mai devreme în primul trimestru al anului viitor, dacă datele de inflație confirmă tendința de scădere și dacă nu apar noi măsuri fiscale”, a comentat Cornel Sava, economist-șef la o bancă comercială.",
          "Pentru cei care au credite cu dobândă variabilă, decizia înseamnă că ratele nu se vor modifica semnificativ în perioada următoare. Indicele IRCC aplicabil în trimestrul următor este de 5,68%.",
          "Următoarea ședință de politică monetară a BNR este programată în noiembrie, când va fi prezentat și noul raport asupra inflației.",
        ],
      },
      {
        outlet: "cotidianulnational",
        title: "Banca Națională nu modifică dobânda-cheie. Ce înseamnă pentru ratele românilor",
        author: "Laura Dima",
        offsetMin: 175,
        quoteBy: "Cornel Sava",
        paragraphs: [
          "Banca Națională a României a lăsat neschimbată dobânda de politică monetară, la 6,50% pe an. Decizia a fost luată marți de consiliul de administrație al băncii centrale.",
          "Rata dobânzii la facilitatea de creditare rămâne la 7,50%, iar cea la facilitatea de depozit la 5,50%. De asemenea, nu au fost modificate rezervele minime obligatorii.",
          "BNR justifică prudența prin nivelul încă ridicat al inflației și prin incertitudinile privind evoluția deficitului bugetar.",
          "„Cred că prima reducere a dobânzii o vom vedea cel mai devreme în primul trimestru al anului viitor, dacă datele de inflație confirmă tendința de scădere și dacă nu apar noi măsuri fiscale”, spune economistul Cornel Sava.",
          "Pentru cei cu credite ipotecare, ratele lunare vor rămâne în mare parte la nivelul actual. Indicele IRCC, folosit la calculul dobânzilor pentru creditele în lei, se situează la 5,68%.",
        ],
      },
      {
        outlet: "actualitateatv",
        title: "Decizie BNR: dobânda de referință rămâne la 6,50%",
        author: "Radu Ciobanu",
        offsetMin: 160,
        quoteBy: "Cornel Sava",
        paragraphs: [
          "Dobânda de referință a Băncii Naționale rămâne la 6,50%, a anunțat marți banca centrală, după ședința de politică monetară. Este a opta ședință consecutivă în care BNR nu modifică nivelul dobânzii-cheie.",
          "Banca centrală spune că inflația se află pe o tendință descendentă, dar că incertitudinile rămân ridicate, inclusiv în privința măsurilor fiscale.",
          "„Cred că prima reducere a dobânzii o vom vedea cel mai devreme în primul trimestru al anului viitor, dacă datele de inflație confirmă tendința de scădere și dacă nu apar noi măsuri fiscale”, a declarat pentru Actualitatea TV economistul Cornel Sava.",
          "Următoarea decizie de politică monetară va fi anunțată în noiembrie.",
        ],
      },
    ],
  },
  {
    id: "inflatie-ins",
    category: "economie",
    image: { scene: "interior", caption: "Raft cu produse alimentare într-un supermarket din București", hue: 100 },
    versions: [
      {
        outlet: "radareconomic",
        title: "Inflația a coborât la 5,1% în august. Alimentele s-au scumpit cel mai puțin din ultimii trei ani",
        author: "Paul Nistor",
        offsetMin: 520,
        quoteBy: "Alina Georgescu",
        paragraphs: [
          "Rata anuală a inflației a scăzut în august la 5,1%, de la 5,6% în iulie, potrivit datelor publicate de Institutul Național de Statistică. Este cel mai redus nivel din ultimele 30 de luni.",
          "Prețurile mărfurilor alimentare au crescut cu 3,2% față de august anul trecut, cel mai mic avans din ultimii trei ani. Mărfurile nealimentare s-au scumpit cu 4,4%, iar serviciile cu 9,3%.",
          "Cele mai mari creșteri de prețuri au fost înregistrate la serviciile de apă, canal și salubritate, la transportul aerian și la chirii.",
          "„Scăderea este susținută mai ales de efectul de bază și de prețurile la alimente. Serviciile rămân problema principală, pentru că acolo contează salariile, iar acestea încă cresc cu peste 10% pe an”, a explicat Alina Georgescu, analist economic.",
          "Banca Națională estimează că rata anuală a inflației va ajunge la 4,6% la finalul anului.",
        ],
      },
      {
        outlet: "stiricarpatice",
        title: "INS: prețurile au crescut în august cu 5,1% față de anul trecut",
        author: "Bogdan Enache",
        offsetMin: 560,
        quoteBy: "Alina Georgescu",
        paragraphs: [
          "Inflația anuală a scăzut în august la 5,1%, arată datele Institutului Național de Statistică. În iulie, rata era de 5,6%.",
          "Serviciile se mențin pe primul loc la scumpiri, cu un avans de 9,3% într-un an. Alimentele s-au scumpit cu 3,2%, iar mărfurile nealimentare cu 4,4%.",
          "Printre produsele care s-au ieftinit față de luna precedentă se numără legumele, fructele proaspete și uleiul. În schimb, au continuat să crească prețurile la cafea, ciocolată și țigări.",
          "„Scăderea este susținută mai ales de efectul de bază și de prețurile la alimente. Serviciile rămân problema principală, pentru că acolo contează salariile, iar acestea încă cresc cu peste 10% pe an”, spune analista Alina Georgescu.",
        ],
      },
    ],
  },
  {
    id: "fabrica-arad",
    category: "economie",
    image: { scene: "landscape", caption: "Terenul din Parcul Industrial Arad-Vest pe care va fi construită fabrica", hue: 80 },
    versions: [
      {
        outlet: "jurnaluldevest",
        title: "Investiție de 180 de milioane de euro la Arad: o fabrică de componente auto va angaja 1.200 de oameni",
        author: "Sorina Balint",
        offsetMin: 700,
        quoteBy: "Dan Crăciun",
        paragraphs: [
          "Un producător european de sisteme electronice pentru automobile va construi o fabrică în Parcul Industrial Arad-Vest. Investiția este estimată la 180 de milioane de euro, iar compania anunță 1.200 de locuri de muncă până în 2029.",
          "Unitatea va produce module de control pentru bateriile mașinilor electrice și va avea o suprafață de 48.000 de metri pătrați. Lucrările de construcție ar urma să înceapă în primăvară.",
          "„Arad are avantajul distanței mici față de clienții noștri din Europa Centrală și al unei tradiții industriale solide. Vom colabora cu universitatea pentru un program de formare dual”, a declarat Dan Crăciun, directorul general al diviziei românești.",
          "Proiectul va primi ajutor de stat de aproximativ 27 de milioane de euro, prin schema pentru investiții regionale. Primăria Arad a anunțat că va extinde rețeaua de transport public până în zona parcului industrial.",
          "Rata șomajului în județul Arad este de 1,4%, printre cele mai scăzute din țară, iar mai multe companii din zonă se confruntă deja cu lipsa forței de muncă.",
        ],
      },
      {
        outlet: "radareconomic",
        title: "Arad atrage o nouă fabrică auto: 180 mil. euro și 27 mil. euro ajutor de stat",
        author: "Paul Nistor",
        offsetMin: 745,
        quoteBy: "Dan Crăciun",
        paragraphs: [
          "Parcul Industrial Arad-Vest va găzdui o fabrică de module electronice pentru baterii auto, o investiție de 180 de milioane de euro. Proiectul a primit aprobare pentru un ajutor de stat de aproximativ 27 de milioane de euro.",
          "Compania estimează că va avea 1.200 de angajați până în 2029, iar producția va începe gradual din 2027. Clădirea va avea 48.000 de metri pătrați.",
          "Investiția vine într-o perioadă în care industria auto europeană își mută o parte din producția de componente pentru vehicule electrice spre Europa Centrală și de Est, unde costurile sunt mai mici.",
          "„Arad are avantajul distanței mici față de clienții noștri din Europa Centrală și al unei tradiții industriale solide. Vom colabora cu universitatea pentru un program de formare dual”, a precizat Dan Crăciun, directorul general al diviziei locale.",
          "Cu o rată a șomajului de 1,4%, județul Arad este unul dintre cele mai tensionate piețe ale muncii din țară, iar angajatorii recrutează tot mai des din județele vecine.",
        ],
      },
    ],
  },
  {
    id: "pnrr-cerere-plata",
    category: "economie",
    image: { scene: "city", caption: "Sediul Comisiei Europene de la Bruxelles", hue: 220 },
    versions: [
      {
        outlet: "radareconomic",
        title: "România a depus ultima cerere de plată din PNRR, în valoare de 2,7 miliarde de euro",
        author: "Diana Voicu",
        offsetMin: 1100,
        quoteBy: "Lucian Barbu",
        paragraphs: [
          "Ministerul Investițiilor și Proiectelor Europene a transmis Comisiei Europene ultima cerere de plată din Planul Național de Redresare și Reziliență, în valoare de aproximativ 2,7 miliarde de euro.",
          "Cererea acoperă 64 de jaloane și ținte, printre care finalizarea unor tronsoane de cale ferată, digitalizarea sistemului de achiziții publice și construcția a 180 de creșe.",
          "„Am îndeplinit țintele asumate pentru această tranșă, iar pentru cele câteva jaloane rămase am transmis deja Comisiei documentația suplimentară”, a declarat Lucian Barbu, secretar de stat în minister.",
          "Până acum, România a încasat aproximativ 12,9 miliarde de euro din PNRR. Termenul pentru îndeplinirea țintelor a expirat la sfârșitul lui august, iar Comisia are la dispoziție până la finalul anului pentru a efectua plățile.",
        ],
      },
    ],
  },
  /* ------------------------------------------------------------------ internațional */
  {
    id: "ue-energie-interconectari",
    category: "international",
    region: "europa",
    image: { scene: "city", caption: "Clădirea Europa, sediul Consiliului European, la Bruxelles", hue: 225 },
    versions: [
      {
        outlet: "actualitateatv",
        title: "Summit la Bruxelles: liderii UE au convenit un fond de 25 de miliarde de euro pentru interconectări energetice",
        author: "Alexandra Neacșu",
        offsetMin: 230,
        quoteBy: "Gabriel Lungu",
        paragraphs: [
          "Liderii statelor membre ale Uniunii Europene au ajuns vineri dimineață, după negocieri care au durat toată noaptea, la un acord privind crearea unui fond de 25 de miliarde de euro pentru interconectări energetice între țări.",
          "Banii vor finanța linii electrice de înaltă tensiune și conducte de gaze și hidrogen, cu prioritate pentru regiunile care depind încă de un singur furnizor sau au capacități reduse de transport transfrontalier.",
          "Statele din Europa Centrală și de Est, inclusiv România, au obținut includerea în listă a coridorului electric care leagă Marea Neagră de Europa Centrală.",
          "„Pentru prima dată avem bani europeni dedicați explicit legăturilor dintre rețelele naționale. Pentru regiunea noastră, asta înseamnă prețuri mai stabile iarna”, a declarat Gabriel Lungu, reprezentantul permanent al României pe lângă UE.",
          "Fondul trebuie aprobat și de Parlamentul European. Primele apeluri de proiecte ar putea fi lansate în a doua jumătate a anului viitor.",
        ],
      },
      {
        outlet: "cotidianulnational",
        title: "Acord la Consiliul European: 25 de miliarde de euro pentru rețelele de energie dintre statele membre",
        author: "Mihai Dragomir",
        offsetMin: 260,
        quoteBy: "Gabriel Lungu",
        paragraphs: [
          "Consiliul European a aprobat, la finalul unui summit de două zile, înființarea unui instrument de 25 de miliarde de euro pentru finanțarea interconectărilor energetice transfrontaliere.",
          "Discuțiile s-au prelungit până vineri dimineață, în principal din cauza modului de alocare a banilor. Statele nordice au cerut ca finanțarea să fie acordată exclusiv pe criterii de eficiență, în timp ce țările din est au insistat pentru prioritizarea regiunilor izolate energetic.",
          "Compromisul final prevede că cel puțin 30% din sume vor merge către proiecte din statele cu grad redus de interconectare.",
          "„Pentru prima dată avem bani europeni dedicați explicit legăturilor dintre rețelele naționale. Pentru regiunea noastră, asta înseamnă prețuri mai stabile iarna”, a explicat ambasadorul Gabriel Lungu, reprezentantul permanent al României la Bruxelles.",
          "Instrumentul urmează să fie negociat cu Parlamentul European în lunile următoare.",
        ],
      },
    ],
  },
  {
    id: "fed-dobanda",
    category: "international",
    region: "sua",
    image: { scene: "city", caption: "Clădirea Rezervei Federale din Washington", hue: 200 },
    versions: [
      {
        outlet: "radareconomic",
        title: "Rezerva Federală a SUA reduce dobânda cu 0,25 puncte procentuale. Bursele americane închid pe plus",
        author: "Paul Nistor",
        offsetMin: 820,
        quoteBy: "Ștefan Moldovan",
        paragraphs: [
          "Rezerva Federală a Statelor Unite a redus miercuri dobânda de referință cu 0,25 puncte procentuale, în intervalul 3,75–4,00%. Decizia a fost luată cu zece voturi pentru și două împotrivă.",
          "Banca centrală americană a invocat încetinirea pieței muncii: economia SUA a creat, în medie, doar 70.000 de locuri de muncă pe lună în ultimul trimestru, iar rata șomajului a urcat la 4,4%.",
          "Indicii bursieri de pe Wall Street au închis ședința în creștere, S&P 500 câștigând 0,8%, iar dolarul s-a depreciat ușor în raport cu euro.",
          "„Pentru România efectul direct este limitat, dar un dolar mai slab și costuri de finanțare mai mici pe piețele internaționale ajută statul să se împrumute mai ieftin”, a explicat Ștefan Moldovan, analist la o societate de administrare a investițiilor din București.",
          "Oficialii Fed au semnalat că mai sunt posibile încă una sau două reduceri până la finalul anului viitor.",
        ],
      },
      {
        outlet: "actualitateatv",
        title: "SUA: Fed taie dobânda pentru a doua oară anul acesta",
        author: "Alexandra Neacșu",
        offsetMin: 800,
        quoteBy: "Ștefan Moldovan",
        paragraphs: [
          "Banca centrală a Statelor Unite a anunțat miercuri seară, ora României, o reducere a dobânzii de referință cu un sfert de punct procentual. Noul interval este de 3,75–4,00%.",
          "Este a doua reducere din acest an. Oficialii de la Washington spun că piața muncii dă semne de răcire, în timp ce inflația s-a stabilizat în jurul valorii de 2,7%.",
          "Două dintre cele douăsprezece voturi din comitetul de politică monetară au fost împotriva deciziei.",
          "„Pentru România efectul direct este limitat, dar un dolar mai slab și costuri de finanțare mai mici pe piețele internaționale ajută statul să se împrumute mai ieftin”, a spus analistul Ștefan Moldovan.",
        ],
      },
    ],
  },
  {
    id: "odesa-drone-port",
    category: "international",
    region: "ucraina",
    image: { scene: "sea", caption: "Portul Odesa, la Marea Neagră", hue: 205 },
    versions: [
      {
        outlet: "actualitateatv",
        title: "Atac cu drone asupra regiunii Odesa: infrastructura portuară, avariată, doi angajați răniți",
        author: "Alexandra Neacșu",
        offsetMin: 110,
        quoteBy: "Olena Marchenko",
        paragraphs: [
          "Regiunea ucraineană Odesa a fost ținta unui atac cu drone în noaptea de joi spre vineri. Autoritățile locale au anunțat că au fost avariate un depozit de cereale și o parte din instalațiile de încărcare ale unui port de pe Dunăre.",
          "Doi angajați ai portului au fost răniți și au primit îngrijiri medicale, iar viața lor nu este în pericol. Incendiul izbucnit la depozit a fost stins după aproximativ patru ore.",
          "Potrivit forțelor aeriene ucrainene, 38 dintre cele 52 de drone lansate în cursul nopții au fost doborâte.",
          "„Activitatea portului va fi reluată parțial în 48 de ore. Exporturile de cereale nu vor fi oprite, dar vor avea întârzieri”, a declarat Olena Marchenko, reprezentantă a administrației regionale.",
          "Ministerul Apărării Naționale de la București a transmis că nu au fost semnalate încălcări ale spațiului aerian românesc în cursul nopții, însă sistemele de supraveghere au fost în alertă în nordul județului Tulcea.",
        ],
      },
      {
        outlet: "stiricarpatice",
        title: "Noapte de atacuri în sudul Ucrainei, aproape de granița cu România. MApN: niciun incident pe teritoriul național",
        author: "Andreea Stoica",
        offsetMin: 135,
        quoteBy: "Olena Marchenko",
        paragraphs: [
          "Un port ucrainean de pe Dunăre, aflat la câțiva kilometri de granița cu România, a fost avariat în urma unui atac cu drone. Două persoane au fost rănite, iar un depozit de cereale a luat foc.",
          "Ministerul Apărării Naționale a anunțat că, pe durata atacului, au fost ridicate de la sol două aeronave F-16 pentru monitorizarea situației aeriene. Nu au fost semnalate încălcări ale spațiului aerian național.",
          "Locuitorii din mai multe localități din nordul județului Tulcea au primit mesaje de alertă RO-Alert, ca măsură de precauție.",
          "„Activitatea portului va fi reluată parțial în 48 de ore. Exporturile de cereale nu vor fi oprite, dar vor avea întârzieri”, a transmis Olena Marchenko, din partea administrației regionale Odesa.",
          "Forțele aeriene ucrainene susțin că au neutralizat 38 din cele 52 de drone lansate.",
        ],
      },
      {
        outlet: "infoest",
        title: "Tulcea: alertă RO-Alert în timpul atacului cu drone de peste Dunăre",
        author: "Tudor Apostol",
        offsetMin: 120,
        quoteBy: "Olena Marchenko",
        image: { scene: "night" },
        paragraphs: [
          "Locuitorii din mai multe localități din nordul județului Tulcea au primit, în noaptea de joi spre vineri, mesaje RO-Alert, în timp ce regiunea ucraineană Odesa era vizată de un atac cu drone.",
          "Pe malul ucrainean al Dunării, un depozit de cereale și instalații portuare au fost avariate. Două persoane au fost rănite ușor.",
          "„Activitatea portului va fi reluată parțial în 48 de ore. Exporturile de cereale nu vor fi oprite, dar vor avea întârzieri”, a transmis Olena Marchenko, reprezentantă a autorităților regionale.",
          "MApN a precizat că nu au fost identificate fragmente de drone pe teritoriul României și că echipele de specialitate au verificat zona de mal a Dunării dimineață.",
          "Autoritățile le reamintesc locuitorilor că, în cazul în care găsesc obiecte suspecte, nu trebuie să se apropie de ele și trebuie să sune la 112.",
        ],
      },
    ],
  },
  {
    id: "moldova-interconectare",
    category: "international",
    region: "moldova",
    image: { scene: "landscape", caption: "Linie electrică de înaltă tensiune în apropiere de Ungheni", hue: 140 },
    versions: [
      {
        outlet: "infoest",
        title: "Linia electrică Iași – Ungheni – Strășeni a intrat în probe tehnologice",
        author: "Tudor Apostol",
        offsetMin: 1020,
        quoteBy: "Victor Rotaru",
        paragraphs: [
          "Linia electrică de înaltă tensiune care leagă Iași de Strășeni, prin Ungheni, a intrat în perioada de probe tehnologice, au anunțat operatorii de transport din România și Republica Moldova.",
          "Linia de 400 de kilovolți are o lungime totală de aproape 160 de kilometri, dintre care 95 pe teritoriul Republicii Moldova, și va permite un transfer de până la 600 de megawați între cele două țări.",
          "„Este cea mai importantă lucrare energetică din ultimii 30 de ani pentru Republica Moldova. Ne reduce dependența de o singură sursă de energie și ne apropie de piața europeană”, a declarat Victor Rotaru, ministrul Energiei de la Chișinău.",
          "Probele vor dura aproximativ două luni, după care linia va intra în exploatare comercială. Proiectul a fost finanțat din granturi europene și printr-un împrumut de la Banca Europeană de Investiții.",
        ],
      },
      {
        outlet: "actualitateatv",
        title: "Republica Moldova, mai aproape de rețeaua europeană: linia de 400 kV cu România, în probe",
        author: "Radu Ciobanu",
        offsetMin: 1060,
        quoteBy: "Victor Rotaru",
        paragraphs: [
          "Republica Moldova face un pas important spre independența energetică: linia electrică de 400 de kilovolți care o leagă de România prin Iași și Ungheni a fost pusă sub tensiune pentru probe.",
          "Noua linie are aproape 160 de kilometri și o capacitate de transfer de 600 de megawați, suficientă pentru a acoperi o parte semnificativă din consumul de vârf al țării vecine.",
          "„Este cea mai importantă lucrare energetică din ultimii 30 de ani pentru Republica Moldova. Ne reduce dependența de o singură sursă de energie și ne apropie de piața europeană”, a spus ministrul Energiei, Victor Rotaru.",
          "Operatorii estimează că linia va funcționa comercial de la începutul iernii.",
        ],
      },
    ],
  },
  {
    id: "gaza-convoi-umanitar",
    category: "international",
    region: "orientul-mijlociu",
    image: { scene: "landscape", caption: "Camioane cu ajutoare umanitare la un punct de trecere", hue: 35 },
    versions: [
      {
        outlet: "actualitateatv",
        title: "Orientul Mijlociu: un convoi de 120 de camioane cu ajutoare a intrat în Gaza, după noi negocieri",
        author: "Alexandra Neacșu",
        offsetMin: 380,
        quoteBy: "Hana Saleh",
        paragraphs: [
          "Un convoi de 120 de camioane cu alimente, medicamente și combustibil a intrat joi în Fâșia Gaza, după ce negociatorii au convenit o pauză umanitară de 12 ore în zona de sud a teritoriului.",
          "Ajutoarele au fost coordonate de agențiile ONU și de Crucea Roșie, iar distribuția a început în aceeași zi în mai multe puncte din Khan Younis și Rafah.",
          "„Este un pas important, dar nevoile sunt de cel puțin cinci ori mai mari. Avem nevoie de acces constant, nu de convoaie ocazionale”, a declarat Hana Saleh, coordonatoare a unei organizații umanitare internaționale.",
          "Discuțiile privind o încetare a focului mai lungă continuă la Cairo, cu mediere egipteană și qatareză.",
        ],
      },
      {
        outlet: "cotidianulnational",
        title: "Pauză umanitară de 12 ore în sudul Fâșiei Gaza. ONU cere acces permanent pentru ajutoare",
        author: "Raluca Tănase",
        offsetMin: 420,
        quoteBy: "Hana Saleh",
        paragraphs: [
          "Agențiile ONU au reușit joi să trimită în sudul Fâșiei Gaza 120 de camioane cu ajutoare umanitare, în timpul unei pauze de 12 ore convenite de părți prin intermediul mediatorilor.",
          "Transportul a inclus alimente, apă potabilă, medicamente și combustibil pentru spitale. Organizațiile umanitare avertizează însă că volumul este departe de necesarul zilnic.",
          "„Este un pas important, dar nevoile sunt de cel puțin cinci ori mai mari. Avem nevoie de acces constant, nu de convoaie ocazionale”, a transmis Hana Saleh, reprezentantă a unei organizații internaționale de ajutor.",
          "Negocierile pentru un armistițiu extins au fost reluate la Cairo. Ministerul Afacerilor Externe de la București a reiterat apelul la protejarea civililor și la respectarea dreptului internațional umanitar.",
        ],
      },
    ],
  },
  {
    id: "taifun-okinawa",
    category: "international",
    region: "asia",
    image: { scene: "sea", caption: "Valuri puternice pe coasta insulei Okinawa", hue: 190 },
    versions: [
      {
        outlet: "actualitateatv",
        title: "Japonia: taifunul Kaito a lovit Okinawa. Zboruri anulate și peste 200.000 de locuințe fără curent",
        author: "Radu Ciobanu",
        offsetMin: 1250,
        quoteBy: "Kenji Arai",
        paragraphs: [
          "Taifunul Kaito a atins vineri insula japoneză Okinawa, cu rafale de vânt de până la 190 de kilometri pe oră. Peste 200.000 de locuințe au rămas fără energie electrică, iar aproape toate zborurile de pe aeroportul din Naha au fost anulate.",
          "Autoritățile au emis ordine de evacuare pentru circa 80.000 de locuitori din zonele de coastă. Până acum au fost raportate 14 persoane rănite ușor.",
          "„Furtuna se deplasează lent spre nord, ceea ce înseamnă că ploile vor persista încă cel puțin două zile”, a declarat Kenji Arai, reprezentant al agenției meteorologice japoneze.",
          "Ministerul Afacerilor Externe de la București a transmis că nu are informații despre cetățeni români afectați și a recomandat celor aflați în zonă să urmeze instrucțiunile autorităților locale.",
        ],
      },
    ],
  },
  {
    id: "china-exporturi",
    category: "international",
    region: "asia",
    image: { scene: "sea", caption: "Containere în portul Shanghai", hue: 15 },
    versions: [
      {
        outlet: "radareconomic",
        title: "Exporturile Chinei au crescut cu 6,3% în august, peste estimări. Livrările către UE, în urcare",
        author: "Paul Nistor",
        offsetMin: 1380,
        quoteBy: "Ana Zamfir",
        paragraphs: [
          "Exporturile Chinei au crescut în august cu 6,3% față de aceeași lună a anului trecut, peste media estimărilor analiștilor, de 4,8%, arată datele publicate de administrația vamală de la Beijing.",
          "Importurile au avansat cu doar 1,1%, iar excedentul comercial a ajuns la 91 de miliarde de dolari. Livrările către Uniunea Europeană au crescut cu 9%, în timp ce exporturile către Statele Unite au scăzut cu 4%.",
          "„Vedem o redirecționare a exporturilor chinezești dinspre piața americană spre Europa și Asia de Sud-Est, mai ales la electronice și vehicule electrice”, a comentat Ana Zamfir, economist specializat în comerț internațional.",
          "Datele vin în contextul în care Comisia Europeană analizează noi măsuri de protecție pentru industria siderurgică și cea auto.",
        ],
      },
    ],
  },
  {
    id: "germania-greva-feroviara",
    category: "international",
    region: "europa",
    image: { scene: "city", caption: "Peron gol într-o gară din Berlin", hue: 0 },
    versions: [
      {
        outlet: "stiricarpatice",
        title: "Germania: grevă de 48 de ore la căile ferate. Ce trebuie să știe românii care călătoresc",
        author: "Bogdan Enache",
        offsetMin: 1500,
        quoteBy: "Cosmin Radu",
        paragraphs: [
          "Sindicatul mecanicilor de locomotivă din Germania a declanșat o grevă de 48 de ore, care afectează atât trenurile de lung parcurs, cât și transportul regional. Operatorul feroviar german estimează că doar 30% dintre trenuri vor circula.",
          "Greva începe sâmbătă la ora 2:00 și se încheie luni la aceeași oră. Sindicatul cere o reducere a programului de lucru și majorări salariale de 8%.",
          "„Călătorii români care au bilete pentru aceste zile le pot folosi ulterior sau pot cere rambursarea integrală. Recomandăm verificarea online a fiecărei curse înainte de plecare”, a declarat Cosmin Radu, consul la Consulatul General al României de la München.",
          "Aeroporturile germane nu sunt afectate de grevă, însă autoritățile se așteaptă la aglomerație pe autostrăzi și în stațiile de autobuze interurbane.",
        ],
      },
    ],
  },
  {
    id: "nato-exercitiu-cincu",
    category: "international",
    region: "europa",
    image: { scene: "landscape", caption: "Poligonul de la Cincu, județul Brașov", hue: 95 },
    versions: [
      {
        outlet: "cotidianulnational",
        title: "Peste 5.000 de militari din zece state NATO participă la un exercițiu la Cincu",
        author: "Mihai Dragomir",
        offsetMin: 1180,
        quoteBy: "Florin Dumitrescu",
        paragraphs: [
          "Peste 5.000 de militari din zece state membre NATO participă, timp de două săptămâni, la un exercițiu multinațional desfășurat în Centrul Național de Instruire Întrunită de la Cincu, județul Brașov.",
          "Exercițiul urmărește testarea capacității de desfășurare rapidă a unei brigăzi multinaționale pe flancul estic. Alături de militarii români participă trupe din Franța, Belgia, Olanda, Portugalia, Spania, Italia, Polonia, SUA și Macedonia de Nord.",
          "„Scenariul este unul defensiv, iar obiectivul este să verificăm cât de repede pot fi integrate forțele aliate într-un comandament comun”, a explicat generalul de brigadă Florin Dumitrescu, directorul exercițiului.",
          "Ministerul Apărării Naționale anunță că în perioada exercițiului vor avea loc deplasări de coloane militare pe drumurile naționale din Brașov și Sibiu și le recomandă șoferilor prudență.",
        ],
      },
      {
        outlet: "actualitateatv",
        title: "Exercițiu NATO de amploare în România: coloane militare pe drumurile din Brașov și Sibiu",
        author: "Cristian Popa",
        offsetMin: 1210,
        quoteBy: "Florin Dumitrescu",
        paragraphs: [
          "Militari din zece țări aliate s-au reunit la Cincu, în județul Brașov, pentru unul dintre cele mai mari exerciții NATO desfășurate anul acesta în România. Aproximativ 5.000 de soldați și 700 de vehicule participă la manevre.",
          "Exercițiul durează două săptămâni și include trageri cu muniție reală, desfășurări de trupe pe distanțe lungi și simularea unor operațiuni de apărare aeriană.",
          "„Scenariul este unul defensiv, iar obiectivul este să verificăm cât de repede pot fi integrate forțele aliate într-un comandament comun”, a spus generalul de brigadă Florin Dumitrescu.",
          "Pe durata exercițiului, pe drumurile naționale din zonă vor circula coloane militare, însoțite de echipaje ale Poliției Militare.",
        ],
      },
    ],
  },
  {
    id: "schimb-prizonieri",
    category: "international",
    region: "ucraina",
    image: { scene: "landscape", caption: "Punct de frontieră, în timpul unui schimb de prizonieri", hue: 60 },
    versions: [
      {
        outlet: "infoest",
        title: "Ucraina și Rusia au efectuat un nou schimb de prizonieri, cu medierea Emiratelor Arabe Unite",
        author: "Mihaela Rusu",
        offsetMin: 1620,
        quoteBy: "Iryna Kovalenko",
        paragraphs: [
          "Ucraina și Rusia au efectuat vineri un nou schimb de prizonieri, în urma căruia 146 de militari ucraineni s-au întors acasă. Același număr de militari ruși a fost predat părții ruse.",
          "Schimbul a fost mediat de Emiratele Arabe Unite și este al patrulea din acest an. Printre cei eliberați se află și răniți care au nevoie de tratament de lungă durată.",
          "„Fiecare om adus acasă contează. Continuăm lucrul pentru următoarea etapă, iar listele sunt deja în discuție”, a declarat Iryna Kovalenko, reprezentantă a coordonării ucrainene pentru prizonierii de război.",
          "Potrivit autorităților de la Kiev, peste 5.000 de militari ucraineni au fost eliberați prin schimburi de la începutul războiului.",
        ],
      },
    ],
  },
];
