import type { Story } from "./content";

/* Național și politică. Persoanele sunt fictive. */
export const STORIES_A: Story[] = [
  {
    id: "cod-portocaliu-ploi",
    category: "national",
    image: { scene: "sky", caption: "Nori de ploaie deasupra zonei subcarpatice", hue: 210 },
    versions: [
      {
        outlet: "actualitateatv",
        title: "Cod portocaliu de ploi în șase județe. ANM avertizează asupra unor cantități de până la 100 de litri pe metru pătrat",
        subheading: "Ce zone sunt vizate",
        author: "Radu Ciobanu",
        offsetMin: 70,
        quoteBy: "Elena Munteanu",
        paragraphs: [
          "Administrația Națională de Meteorologie a emis o avertizare cod portocaliu de ploi abundente pentru județele Vâlcea, Argeș, Dâmbovița, Prahova, Buzău și Vrancea, valabilă de sâmbătă, de la ora 10:00, până duminică, la ora 22:00.",
          "Potrivit meteorologilor, în zona de munte și de deal a acestor județe vor cădea, în intervale scurte, între 60 și 80 de litri pe metru pătrat, iar izolat cantitățile pot depăși 100 de litri pe metru pătrat. Pe arii extinse, ploile vor fi însoțite de descărcări electrice și intensificări ale vântului.",
          "Restul țării se află sub cod galben de instabilitate atmosferică, cu averse torențiale, grindină și vijelii, în special în Transilvania și Moldova.",
          "„Este vorba despre un sistem care va staționa aproape 36 de ore deasupra Carpaților de Curbură, iar solul este deja saturat după ploile din ultima săptămână. Riscul de viituri pe râurile mici este ridicat”, a explicat Elena Munteanu, meteorolog-șef de serviciu la ANM.",
          "Hidrologii au emis, la rândul lor, o atenționare cod galben pentru bazinele Buzăului, Ialomiței și Argeșului. Inspectoratele pentru Situații de Urgență din zonele vizate au anunțat că echipajele sunt în alertă și că au fost suplimentate stocurile de saci de nisip.",
          "Autoritățile le recomandă șoferilor să evite deplasările neesențiale pe drumurile din zona montană și să nu traverseze cursurile de apă cu autoturismul.",
        ],
      },
      {
        outlet: "stiricarpatice",
        title: "Avertizare meteo: ploi torențiale în Carpații de Curbură, cod portocaliu până duminică seara",
        author: "Andreea Stoica",
        offsetMin: 95,
        quoteBy: "Elena Munteanu",
        paragraphs: [
          "Șase județe din sudul și estul țării intră de sâmbătă dimineață sub cod portocaliu de ploi, a anunțat ANM. Avertizarea vizează Vâlcea, Argeș, Dâmbovița, Prahova, Buzău și Vrancea și rămâne în vigoare până duminică, la ora 22:00.",
          "Meteorologii estimează cantități de apă de 60–80 de litri pe metru pătrat, iar pe suprafețe restrânse, mai ales la munte, de peste 100 de litri. În aceeași perioadă, pentru cea mai mare parte a țării este valabil un cod galben de averse, vânt puternic și grindină.",
          "Specialiștii spun că pericolul principal nu îl reprezintă doar cantitatea de precipitații, ci și faptul că ploile din zilele trecute au îmbibat deja terenul. „Este vorba despre un sistem care va staționa aproape 36 de ore deasupra Carpaților de Curbură, iar solul este deja saturat după ploile din ultima săptămână. Riscul de viituri pe râurile mici este ridicat”, a declarat Elena Munteanu, meteorolog-șef de serviciu la ANM.",
          "Institutul Național de Hidrologie a emis o atenționare cod galben pentru râurile din bazinele Buzău, Ialomița și Argeș, unde sunt posibile scurgeri importante pe versanți și creșteri rapide de debite.",
          "Prefecturile din județele afectate au convocat comitetele pentru situații de urgență, iar ISU a pregătit motopompe și bărci pentru eventuale intervenții.",
        ],
      },
      {
        outlet: "infoest",
        title: "Vrancea și Buzău, sub cod portocaliu de ploi. Ce recomandă autoritățile",
        author: "Mihaela Rusu",
        offsetMin: 140,
        quoteBy: "Elena Munteanu",
        image: { scene: "mountain" },
        paragraphs: [
          "Județele Vrancea și Buzău se numără printre cele șase pentru care meteorologii au emis cod portocaliu de ploi abundente, începând de sâmbătă de la ora 10:00. Avertizarea mai include Vâlcea, Argeș, Dâmbovița și Prahova.",
          "În zonele de deal și de munte sunt așteptate cantități de 60–80 de litri pe metru pătrat, izolat de peste 100. Localitățile de pe văile Buzăului și Putnei, afectate de inundații și în anii trecuți, sunt monitorizate cu prioritate.",
          "„Este vorba despre un sistem care va staționa aproape 36 de ore deasupra Carpaților de Curbură, iar solul este deja saturat după ploile din ultima săptămână. Riscul de viituri pe râurile mici este ridicat”, a precizat Elena Munteanu, de la ANM.",
          "ISU Vrancea a anunțat că a pregătit 12 echipaje de intervenție și că primăriile din zona montană au primit instrucțiuni pentru avertizarea rapidă a populației. Localnicii sunt sfătuiți să-și pună la adăpost animalele și bunurile din gospodăriile aflate aproape de albii.",
          "Codul portocaliu expiră duminică la ora 22:00. Până atunci, restul regiunii rămâne sub cod galben de instabilitate atmosferică.",
        ],
      },
    ],
  },
  {
    id: "accident-dn1-prahova",
    category: "national",
    sensitive: true,
    image: { scene: "road", caption: "Trafic dirijat pe DN1, în zona localității Bănești", hue: 30 },
    versions: [
      {
        outlet: "actualitateatv",
        title: "Accident grav pe DN1, în Prahova: două persoane au murit, alte trei au fost rănite",
        author: "Cristian Popa",
        offsetMin: 180,
        quoteBy: "Adrian Neagu",
        paragraphs: [
          "Două persoane și-au pierdut viața, iar alte trei au fost rănite în urma unui accident rutier produs vineri seară pe DN1, în apropierea localității Bănești, județul Prahova. În eveniment au fost implicate un autoturism și o autoutilitară.",
          "Potrivit primelor informații ale polițiștilor, șoferul autoturismului, un bărbat de 41 de ani, ar fi pătruns pe contrasens într-o curbă și a intrat în coliziune cu autoutilitara care circula regulamentar spre Brașov. Circumstanțele exacte urmează să fie stabilite de anchetatori.",
          "La fața locului au intervenit trei echipaje SMURD, două ambulanțe și o autospecială de descarcerare. Cele trei persoane rănite au fost transportate la Spitalul Județean de Urgență Ploiești, iar starea uneia dintre ele este considerată gravă.",
          "„Circulația a fost blocată complet timp de aproape trei ore și a fost deviată pe rute ocolitoare. În prezent, traficul se desfășoară pe un singur sens, dirijat de polițiști”, a declarat Adrian Neagu, purtătorul de cuvânt al IPJ Prahova.",
          "Polițiștii au deschis un dosar penal pentru ucidere din culpă și vătămare corporală din culpă. Ambii șoferi au fost testați cu aparatul etilotest, iar rezultatele au fost negative.",
        ],
      },
      {
        outlet: "stiricarpatice",
        title: "Tragedie pe Valea Prahovei: coliziune între o mașină și o autoutilitară, doi morți",
        subheading: "Ancheta polițiștilor",
        author: "Bogdan Enache",
        offsetMin: 205,
        quoteBy: "Adrian Neagu",
        paragraphs: [
          "Un accident rutier petrecut vineri seară pe DN1, la ieșirea din Bănești, s-a soldat cu doi morți și trei răniți. Un autoturism care circula dinspre Brașov spre Ploiești s-a ciocnit frontal cu o autoutilitară.",
          "Echipajele sosite la fața locului au găsit două dintre victime fără semne vitale. Cadrele medicale au declarat decesul după manevre de resuscitare. Alte trei persoane, între care un bărbat aflat în stare gravă, au fost duse la spitalul din Ploiești.",
          "Anchetatorii verifică ipoteza potrivit căreia conducătorul auto de 41 de ani ar fi pătruns pe contrasens într-o curbă. Ambii șoferi au fost testați cu etilotestul, iar rezultatele au fost negative.",
          "„Circulația a fost blocată complet timp de aproape trei ore și a fost deviată pe rute ocolitoare. În prezent, traficul se desfășoară pe un singur sens, dirijat de polițiști”, a precizat Adrian Neagu, purtător de cuvânt al Poliției Prahova.",
          "Cercetările continuă într-un dosar penal pentru ucidere din culpă și vătămare corporală din culpă. Polițiștii le recomandă șoferilor care tranzitează Valea Prahovei în acest weekend să consulte aplicațiile de trafic înainte de plecare.",
        ],
      },
    ],
  },
  {
    id: "metrou-m6-tunel",
    category: "national",
    image: { scene: "interior", caption: "Șantierul stației de metrou 1 Mai, magistrala M6", hue: 45 },
    versions: [
      {
        outlet: "cotidianulnational",
        title: "Metroul spre Aeroportul Otopeni: prima mașină de forat a terminat tunelul de 1,8 kilometri",
        author: "Laura Dima",
        offsetMin: 320,
        quoteBy: "Sorin Vlad",
        paragraphs: [
          "Prima mașină de forat tuneluri folosită pe magistrala M6 a finalizat tronsonul de 1,8 kilometri dintre stațiile 1 Mai și Pajura, a anunțat Metrorex. Lucrarea a durat 14 luni, cu aproximativ două luni mai puțin decât estimarea inițială.",
          "A doua mașină, care sapă tubul paralel, se află la aproximativ 400 de metri de punctul final. După finalizarea forajelor vor începe lucrările de arhitectură în stații, montarea căii de rulare și a instalațiilor.",
          "„Suntem în grafic pe tronsonul subteran, iar ținta noastră rămâne punerea în funcțiune a primei secțiuni, până la Tokyo, în 2028”, a declarat Sorin Vlad, director tehnic în cadrul Metrorex.",
          "Magistrala M6 va avea 14 kilometri și 12 stații și va lega Gara de Nord de Aeroportul Henri Coandă. Proiectul, evaluat la aproximativ 1,6 miliarde de euro, este finanțat în principal din fonduri europene și printr-un împrumut de la Agenția Japoneză pentru Cooperare Internațională.",
        ],
      },
      {
        outlet: "stiricarpatice",
        title: "M6: Metrorex anunță finalizarea primului tunel între 1 Mai și Pajura",
        author: "Andreea Stoica",
        offsetMin: 355,
        quoteBy: "Sorin Vlad",
        paragraphs: [
          "Tunelul dintre stațiile 1 Mai și Pajura ale viitoarei magistrale de metrou M6 a fost străpuns complet, după 14 luni de lucru. Este primul tronson de 1,8 kilometri finalizat pe linia care va face legătura cu Aeroportul Otopeni.",
          "Constructorul a lucrat cu două mașini de forat în paralel. Cea de-a doua mai are de săpat circa 400 de metri, iar reprezentanții Metrorex spun că foarte probabil va ieși la suprafață până la finalul anului.",
          "Linia va avea în total 12 stații și o lungime de 14 kilometri. Costul estimat al proiectului se ridică la aproximativ 1,6 miliarde de euro, bani proveniți din fonduri europene și dintr-un credit japonez.",
          "„Suntem în grafic pe tronsonul subteran, iar ținta noastră rămâne punerea în funcțiune a primei secțiuni, până la Tokyo, în 2028”, a spus Sorin Vlad, directorul tehnic al companiei.",
          "Locuitorii din zona Pajura reclamă de luni bune restricțiile de trafic din jurul șantierului. Metrorex promite că o parte dintre acestea vor fi ridicate după finalizarea celui de-al doilea tunel.",
        ],
      },
    ],
  },
  {
    id: "cluj-parcari-resedinta",
    category: "national",
    image: { scene: "city", caption: "Cartierul Mănăștur din Cluj-Napoca", hue: 190 },
    versions: [
      {
        outlet: "jurnaluldevest",
        title: "Cluj-Napoca: aproape 3.000 de locuri noi de parcare de reședință până în primăvară",
        author: "Vlad Mureșan",
        offsetMin: 460,
        quoteBy: "Oana Filip",
        paragraphs: [
          "Primăria Cluj-Napoca a lansat licitația pentru amenajarea a patru parcări supraetajate în cartierele Mănăștur, Gheorgheni și Mărăști, care vor adăuga în total 2.860 de locuri de parcare de reședință.",
          "Valoarea estimată a contractelor este de 96 de milioane de lei, fără TVA, iar termenul de execuție este de 18 luni de la semnarea contractelor. Pe acoperișurile clădirilor vor fi amenajate terenuri de sport și spații verzi.",
          "„Am ales amplasamente pe care există deja parcări la sol, astfel încât să nu tăiem niciun copac și să eliberăm, în paralel, trotuarele ocupate de mașini”, a declarat Oana Filip, arhitect-șef al municipiului.",
          "În prezent, pe lista de așteptare pentru un loc de parcare de reședință se află peste 11.000 de clujeni. Primăria spune că alocarea noilor locuri se va face online, pe baza unui punctaj care ține cont de vechimea cererii.",
        ],
      },
    ],
  },
  {
    id: "iasi-dosar-fonduri",
    category: "national",
    sensitive: true,
    image: { scene: "city", caption: "Sediul Tribunalului Iași", hue: 25 },
    versions: [
      {
        outlet: "infoest",
        title: "Iași: administratorul unei firme de construcții, reținut într-un dosar privind fonduri europene",
        author: "Tudor Apostol",
        offsetMin: 250,
        quoteBy: "Carmen Ionescu",
        paragraphs: [
          "Un bărbat de 52 de ani, administrator al unei firme de construcții din Iași, a fost reținut pentru 24 de ore de procurori, într-un dosar în care se fac cercetări pentru obținerea pe nedrept de fonduri europene.",
          "Anchetatorii suspectează că firma ar fi prezentat documente care nu corespundeau realității pentru a obține finanțare de aproximativ 3,2 milioane de lei, destinată modernizării unei hale de producție din zona metropolitană a Iașului.",
          "Joi dimineață au avut loc cinci percheziții, la sediile firmei și la locuințele unor persoane apropiate. Au fost ridicate documente contabile și echipamente electronice.",
          "„Persoana reținută beneficiază de prezumția de nevinovăție. Procurorii vor decide în cursul zilei de vineri dacă solicită instanței măsuri preventive”, a precizat Carmen Ionescu, purtător de cuvânt al Parchetului de pe lângă Tribunalul Iași.",
          "Reprezentanții firmei nu au putut fi contactați până la publicarea acestui articol. Vom reveni cu informații după ce vom primi un punct de vedere.",
        ],
      },
      {
        outlet: "cotidianulnational",
        title: "Percheziții la Iași într-o anchetă privind fonduri europene de 3,2 milioane de lei. Un om de afaceri a fost reținut",
        author: "Laura Dima",
        offsetMin: 285,
        quoteBy: "Carmen Ionescu",
        paragraphs: [
          "Procurorii au efectuat joi cinci percheziții în municipiul Iași și în două comune învecinate, într-un dosar în care sunt investigate posibile nereguli la accesarea unor fonduri europene. În urma audierilor, administratorul unei firme de construcții a fost reținut pentru 24 de ore.",
          "Potrivit anchetatorilor, compania ar fi folosit documente care nu corespundeau realității pentru a obține aproximativ 3,2 milioane de lei, bani care ar fi trebuit să finanțeze modernizarea unei hale de producție.",
          "„Persoana reținută beneficiază de prezumția de nevinovăție. Procurorii vor decide în cursul zilei de vineri dacă solicită instanței măsuri preventive”, a transmis Carmen Ionescu, purtătorul de cuvânt al parchetului.",
          "Anchetatorii au ridicat documente contabile și mai multe laptopuri. Fondurile au fost obținute printr-un program regional destinat IMM-urilor, derulat în perioada 2021–2023.",
          "Avocatul bărbatului nu a dorit să facă declarații. Ancheta este în desfășurare.",
        ],
      },
    ],
  },
  /* ------------------------------------------------------------------ politică */
  {
    id: "buget-rectificativ",
    category: "politica",
    image: { scene: "city", caption: "Palatul Victoria, sediul Guvernului", hue: 215 },
    versions: [
      {
        outlet: "cotidianulnational",
        title: "Guvernul a aprobat rectificarea bugetară: bani în plus pentru investiții și pensii, tăieri la cheltuielile de funcționare",
        subheading: "Unde se duc banii",
        author: "Mihai Dragomir",
        offsetMin: 40,
        quoteBy: "Andrei Pavel",
        paragraphs: [
          "Guvernul a aprobat joi seară prima rectificare bugetară din acest an, care păstrează ținta de deficit la 6,4% din PIB. Ministerele primesc în total 7,8 miliarde de lei în plus, bani redistribuiți în principal din cheltuielile de funcționare ale administrației centrale.",
          "Cele mai mari sume suplimentare merg la Ministerul Transporturilor, pentru plata lucrărilor la autostrăzi, și la bugetul de pensii, unde sunt necesare 2,1 miliarde de lei pentru recalculările aflate în curs.",
          "„Nu majorăm deficitul. Mutăm bani de acolo de unde nu au fost cheltuiți către proiectele care au facturi de plătit până la sfârșitul anului”, a declarat ministrul Finanțelor, Andrei Pavel, la finalul ședinței de Guvern.",
          "Pe de altă parte, cheltuielile cu bunuri și servicii ale ministerelor sunt reduse cu 5%, iar mai multe programe care nu au fost demarate până în septembrie își pierd finanțarea pentru anul în curs.",
          "Ministrul a precizat că estimarea de creștere economică a fost revizuită de la 2,8% la 2,3%, pe fondul încetinirii din zona euro. Proiectul de rectificare urmează să fie publicat în Monitorul Oficial.",
        ],
      },
      {
        outlet: "stiricarpatice",
        title: "Rectificare bugetară: Executivul redistribuie 7,8 miliarde de lei, deficitul rămâne la 6,4%",
        author: "Bogdan Enache",
        offsetMin: 55,
        quoteBy: "Andrei Pavel",
        paragraphs: [
          "Executivul a adoptat rectificarea bugetară prin care 7,8 miliarde de lei sunt mutate între ministere, fără ca ținta de deficit bugetar să fie modificată. Aceasta rămâne la 6,4% din produsul intern brut.",
          "Transporturile și sistemul de pensii sunt principalii beneficiari. În schimb, cheltuielile curente ale ministerelor scad cu 5%, iar programele nedemarate până în septembrie rămân fără bani în acest an.",
          "„Nu majorăm deficitul. Mutăm bani de acolo de unde nu au fost cheltuiți către proiectele care au facturi de plătit până la sfârșitul anului”, a explicat Andrei Pavel, ministrul Finanțelor.",
          "Guvernul și-a redus totodată prognoza de creștere economică pentru acest an, la 2,3%, față de 2,8% cât estima în primăvară.",
        ],
      },
      {
        outlet: "actualitateatv",
        title: "Andrei Pavel, după rectificarea bugetară: „Nu majorăm deficitul”",
        author: "Ioana Marin",
        offsetMin: 30,
        quoteBy: "Andrei Pavel",
        paragraphs: [
          "Ministrul Finanțelor, Andrei Pavel, a prezentat joi seară, după ședința de Guvern, principalele prevederi ale rectificării bugetare, prima din acest an.",
          "„Nu majorăm deficitul. Mutăm bani de acolo de unde nu au fost cheltuiți către proiectele care au facturi de plătit până la sfârșitul anului”, a spus ministrul, întrebat dacă ținta de 6,4% din PIB mai poate fi atinsă.",
          "În total, sunt realocate 7,8 miliarde de lei. Ministerul Transporturilor primește fonduri suplimentare pentru plata constructorilor de autostrăzi, iar bugetul de pensii este completat cu 2,1 miliarde de lei.",
          "Ministrul a recunoscut că economia crește mai lent decât se anticipa și a anunțat că prognoza oficială a fost coborâtă la 2,3%. El a exclus, deocamdată, majorarea unor taxe până la finalul anului.",
        ],
      },
      {
        outlet: "radareconomic",
        title: "Rectificarea bugetară în cifre: +2,1 mld. lei la pensii, -5% la bunuri și servicii, prognoză de creștere redusă la 2,3%",
        author: "Diana Voicu",
        offsetMin: 25,
        quoteBy: "Andrei Pavel",
        paragraphs: [
          "Prima rectificare bugetară a anului mută 7,8 miliarde de lei între ordonatorii de credite și menține ținta de deficit cash la 6,4% din PIB, potrivit proiectului aprobat joi de Guvern.",
          "Bugetul asigurărilor sociale de stat primește 2,1 miliarde de lei, iar Transporturile aproximativ 2,6 miliarde de lei. Cheltuielile cu bunuri și servicii ale ministerelor sunt reduse cu 5%, măsură care ar trebui să economisească circa 1,4 miliarde de lei.",
          "Analiștii consultați de Radar Economic spun că menținerea țintei depinde de încasările din TVA din ultimul trimestru, care au fost sub așteptări în primele opt luni.",
          "„Nu majorăm deficitul. Mutăm bani de acolo de unde nu au fost cheltuiți către proiectele care au facturi de plătit până la sfârșitul anului”, a spus ministrul Finanțelor, Andrei Pavel.",
          "Guvernul a revizuit în jos prognoza de creștere economică, la 2,3%, iar produsul intern brut nominal estimat pentru acest an este acum de 1.920 de miliarde de lei.",
        ],
      },
    ],
  },
  {
    id: "senat-stare-civila-digitala",
    category: "politica",
    image: { scene: "interior", caption: "Plenul Senatului, în timpul votului final", hue: 20 },
    versions: [
      {
        outlet: "stiricarpatice",
        title: "Senatul a adoptat legea care permite eliberarea online a certificatelor de naștere și căsătorie",
        author: "Andreea Stoica",
        offsetMin: 600,
        quoteBy: "Victor Ilie",
        paragraphs: [
          "Senatul a adoptat, în calitate de for decizional, proiectul de lege care permite solicitarea și eliberarea online a certificatelor de stare civilă. Proiectul a primit 98 de voturi pentru, 12 împotrivă și 7 abțineri.",
          "Potrivit noii legi, cetățenii vor putea cere duplicate ale certificatelor de naștere, căsătorie sau deces printr-o platformă națională, cu autentificare prin identitatea electronică. Documentele vor fi emise în format electronic, cu semnătură calificată.",
          "„Vorbim de aproximativ 1,5 milioane de solicitări pe an care astăzi presupun cel puțin o deplasare la ghișeu. Din 2027, majoritatea se vor rezolva de acasă”, a declarat senatorul Victor Ilie, inițiatorul proiectului.",
          "Legea urmează să fie trimisă la promulgare. Ministerul de Interne are la dispoziție 12 luni pentru a pune în funcțiune platforma.",
        ],
      },
      {
        outlet: "cotidianulnational",
        title: "Actele de stare civilă, și online: votul final a fost dat în Senat",
        author: "Mihai Dragomir",
        offsetMin: 640,
        quoteBy: "Victor Ilie",
        paragraphs: [
          "Românii nu vor mai fi nevoiți să meargă la primărie pentru un duplicat al certificatului de naștere sau de căsătorie. Senatul a votat marți, cu 98 de voturi pentru, legea care digitalizează eliberarea actelor de stare civilă.",
          "Solicitările vor putea fi depuse pe o platformă administrată de Ministerul Afacerilor Interne, iar documentele vor fi emise electronic și vor avea aceeași valoare juridică precum cele pe hârtie.",
          "Inițiatorul proiectului, senatorul Victor Ilie, a explicat în plen că sistemul va reduce semnificativ cozile de la ghișee. „Vorbim de aproximativ 1,5 milioane de solicitări pe an care astăzi presupun cel puțin o deplasare la ghișeu. Din 2027, majoritatea se vor rezolva de acasă”, a spus acesta.",
          "Opoziția a criticat termenul de implementare de 12 luni, pe care îl consideră prea scurt, având în vedere întârzierile altor proiecte de digitalizare.",
          "Legea merge acum la promulgare.",
        ],
      },
    ],
  },
  {
    id: "motiune-transporturi",
    category: "politica",
    image: { scene: "interior", caption: "Ședință comună a Camerei Deputaților și Senatului", hue: 10 },
    versions: [
      {
        outlet: "actualitateatv",
        title: "Moțiunea simplă împotriva ministrului Transporturilor a fost respinsă de deputați",
        author: "Ioana Marin",
        offsetMin: 780,
        quoteBy: "Mihai Toma",
        paragraphs: [
          "Camera Deputaților a respins miercuri moțiunea simplă depusă de opoziție împotriva ministrului Transporturilor, Mihai Toma. Au votat pentru 112 deputați, iar împotrivă 176.",
          "Semnatarii moțiunii i-au reproșat ministrului întârzierile de pe mai multe loturi de autostradă și situația materialului rulant de la CFR Călători, unde aproape o treime dintre trenuri au peste 40 de ani vechime.",
          "În discursul său, ministrul a prezentat calendarul lucrărilor aflate în desfășurare. „Anul acesta vom deschide circulației peste 150 de kilometri de autostradă, cel mai mult din ultimul deceniu. Pentru trenuri, primele 20 de rame noi intră în circulație în primăvară”, a spus Mihai Toma.",
          "Este a doua moțiune simplă respinsă în această sesiune parlamentară.",
        ],
      },
    ],
  },
  {
    id: "reforma-bacalaureat",
    category: "politica",
    image: { scene: "interior", caption: "Elevi în sala de examen", hue: 50 },
    versions: [
      {
        outlet: "cotidianulnational",
        title: "Ministrul Educației propune un nou bacalaureat: probă de competențe digitale obligatorie, subiecte mai puține la română",
        author: "Raluca Tănase",
        offsetMin: 910,
        quoteBy: "Irina Dobre",
        paragraphs: [
          "Ministerul Educației a pus în dezbatere publică noua metodologie pentru examenul de bacalaureat, care ar urma să se aplice începând cu promoția 2028. Principala schimbare este introducerea unei probe scrise obligatorii de competențe digitale.",
          "Proba de limba și literatura română ar urma să aibă două subiecte în loc de trei, însă cu un accent mai mare pe argumentare și pe înțelegerea textelor nonliterare. Durata examenului rămâne de trei ore.",
          "„Nu vrem un examen mai ușor, ci unul care să verifice ceea ce elevii chiar folosesc după liceu”, a declarat ministrul Educației, Irina Dobre, într-o conferință de presă.",
          "Dezbaterea publică durează 30 de zile. Sindicatele din învățământ au cerut ca noile programe să fie publicate cu cel puțin doi ani înaintea primei sesiuni de examen.",
        ],
      },
      {
        outlet: "infoest",
        title: "Bacalaureat 2028: ce se schimbă, potrivit propunerii Ministerului Educației",
        author: "Mihaela Rusu",
        offsetMin: 960,
        quoteBy: "Irina Dobre",
        paragraphs: [
          "Elevii care încep acum clasa a XI-a ar putea susține un bacalaureat diferit de cel de astăzi. Ministerul Educației a publicat un proiect de metodologie care introduce o probă obligatorie de competențe digitale și reduce numărul subiectelor de la proba de limba română.",
          "Potrivit proiectului, la română vor fi două subiecte, iar unul dintre ele va presupune analiza unui text de presă sau a unui document oficial. Proba de competențe digitale va fi susținută în scris, în centre de examen dotate cu calculatoare.",
          "„Nu vrem un examen mai ușor, ci unul care să verifice ceea ce elevii chiar folosesc după liceu”, a explicat ministrul Irina Dobre.",
          "Directorii de licee din Iași și Suceava consultați de Info Est spun că mai multe școli din mediul rural nu au încă laboratoare de informatică suficiente pentru a găzdui proba. Ministerul susține că dotarea va fi finalizată din fonduri europene până în 2027.",
          "Propunerea este în dezbatere publică timp de 30 de zile.",
        ],
      },
    ],
  },
];
